### PR TITLE
feat: replace gorilla/mux with labstack/echo

### LINKED ISSUE #378: Replace gorilla/mux with echo library
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for dependencies

### Description [**REQUIRED**]
According to the TSC decision, we should replace gorilla/mux with echo library.

### PR DESCRIPTION
**Pull request by FelixTing**
closes: #378 

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Run make docker to build the image
From the latest compose-builder run `make run no-secty device-dev ds-onvif-camera`
Set the log level of device-onvif-camera to `DEBUG`
Verify the device-onvif-camera service bootstraps successfully and contains the following log message:
```
level=INFO ts=2023-08-28T04:27:18.179454Z app=device-onvif-camera source=basenotificationresthandler.go:53 msg="Route /api/v3/onvifevent/:deviceName/:resourceName added."
```
Send an ONVIF notification by executing the following command:
```
curl -X POST localhost:59984/api/v3/onvifevent/test/test
```
Verify the log contains the following message:
```
level=DEBUG ts=2023-08-28T04:27:21.803792Z app=device-onvif-camera source=basenotificationresthandler.go:62 msg="Received POST for Device=test Resource=test"

```

### CODE REVIEW

**Comment by lenny-goodell** [comment]
@FelixTing , this is not a breaking change since  changing the signature of processAsyncRequest does not impact the use of this service. I.e. internal changes like this are not Breaking Changes. Please update the commit message and PR description to remove the Breaking Change details.

**Review by lenny-goodell — COMMENTED** [review]
LGTM, but @ajcasagrande and team should review and test.

**Review by presatish — CHANGES_REQUESTED** [review]
LGTM except copyright for a file needs to be updated. I ran the services with the new image. ONVIF camera was discovered and added when right credentials were provided. I tested some apis and also streaming.

**Comment by FelixTing** [comment]
Updated copyright.
@presatish Thank you for testing.

**Review by presatish — APPROVED** [review]
LGTM

**Pull request merged**
