### PR TITLE
refactor!: prefix some commands with onvif service name and add SnapshotUri

### PR DESCRIPTION
**Pull request by ajcasagrande**
BREAKING CHANGE: Changed the name of many device commands to include a prefix of the onvif service they belong to. For example Status becomes PTZStatus, Profiles becomes MediaProfiles, etc.

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **n/a**
- [ ] **TODO** I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] **TODO** I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Make sure to **clean edgex**

- Build and run latest edgex main and this branch of device-onvif-camera
- Import the device-onvif-camera postman collection
- Import the postman env file if not done already
- Update postman env with your camera's values
- Run the postman collection
- Verify commands work as they did before

### CODE REVIEW

**Review by vyshali-chitikeshi — CHANGES_REQUESTED** [review]
snapshot uri api needs to change port number 59882 in device-onvif postman collection

**Review by ChristianDarr-personal — DISMISSED** [review]
LGTM, other than Vyshali's suggestions

**Comment by vchitike** [comment]
Executed several updated api's and they all seems to be working correctly. Validation perspective updating api names looks good, however all api execution will be done as part of release validation.

**Review by presatish — APPROVED** [review]
LGTM

**Review by presatish — DISMISSED** [review]
LGTM

**Review by vyshali-chitikeshi — DISMISSED** [review]
Updated code looks good for snapshot uri api port number

**Review by presatish — APPROVED** [review]

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Pull request merged**
