### PR TITLE
feat: Add GetSnapshot func

### LINKED ISSUE #49: Service should support ONVIF snapshots
As discussed at today's TSC meeting since the plan is to deprecate the existing device-camera service once this service has been released, we should ensure that this service provides the capability to capture camera snapshots (e.g. see the `OnvifSnapshot` device resources in the old service), as otherwise we're not replacing the existing functionality.

### PR DESCRIPTION
**Pull request by weichou1229**
Close #49 
Signed-off-by: bruce <weichou1229@gmail.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)  **not impact the test**
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the new behavior?
Add a custom func to get the snapshot binary data from the camera

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by weichou1229** [comment]
@tonyespy PR opened, could you help view it? 
The lib also changed https://github.com/edgexfoundry-holding/device-onvif-camera/pull/57

**Comment by cloudxxx8** [comment]
please update go.mod to use the new onvif lib

**Comment by weichou1229** [comment]
Updated.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@tonyespy since the community is moving the repository, I would like to merge this PR first.  please open new issues if you found anything wrong.

**Pull request merged**
