### PR TITLE
build: Upgrade sdk and paho.mqtt lib

### PR DESCRIPTION
**Pull request by weichou1229**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features) **not impact the test**
- [ ] Docs have been added / updated (for bug fixes / features) **not impact the doc**

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the new behavior?

- Upgrade sdk to v2.2.1-dev.5
- Upgrade paho.mqtt to v1.4.1

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lenny-goodell** [comment]
@cloudxxx8 , 
   FYI, the plan is to release the new Camera services for Kamakura, so we'll need to revert these changes prior to release.

**Comment by cloudxxx8** [comment]
@lenny-intel sorry, I didn't realize that.
instead of revert this changes, may we open another Kamakura branch and open the PR to change back the go.mod and Attribution.txt before the release?
Do you know which issues of this repository are must-fix for the release?

**Comment by lenny-goodell** [comment]
@cloudxxx8 , I think it is simple enough to switch back to the v2.2.0 SDK. 
The Intel team has been working on prioritizing the issues. I don't have the list my self, but will try to get the team to label the ones for release as high. 
@ajcasagrande, FYI.

**Comment by cloudxxx8** [comment]
ok, let me revert it for now

**Pull request merged**
