### PR TITLE
refactor!: consume device-sdk-go breaking changes

### PR DESCRIPTION
**Pull request by weichou1229**
BREAKING CHANGE: update ProtocolDriver implementation for the new ProtocolDriver interface changes

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break). update ProtocolDriver implementation for the new ProtocolDriver interface changes
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) not impact
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) not impact
  <link to docs PR>

## Testing Instructions

- set up a camera
- run core services, consul, device-onvif-camera
- test the ONVIF API
- run make unittest

### CODE REVIEW

**Review by presatish — COMMENTED** [review]
@weichou1229 Please change the copyright for these files from `2022` to `2022-2023`

**Review by vyshali-chitikeshi — COMMENTED** [review]
In non secure mode, everything works correctly. able to add cameras and credentials and api execution works. But in secure mode, while entering credentials with map_credentials.sh script it gives `401` error. attached screenshot of script output and onvif logs.

Note that issue does not exist with device-onvif main branch code.

**Comment by vyshali-chitikeshi** [comment]
Screenshot from 2023-03-14 12-02-11
[_edgex-device-onvif-camera_logs (61).txt](https://github.com/edgexfoundry/device-onvif-camera/files/10996545/_edgex-device-onvif-camera_logs.61.txt)

**Comment by vchitike** [comment]
[map_credentials_script_error.txt](https://github.com/edgexfoundry/device-onvif-camera/files/10996552/map_credentials_script_error.txt)
[_edgex-device-onvif-camera_logs (61).txt](https://github.com/edgexfoundry/device-onvif-camera/files/10996553/_edgex-device-onvif-camera_logs.61.txt)

**Comment by lenny-goodell** [comment]
@vyshali-chitikeshi , remember in secure mode you now need to get the token and pass it in the header

**Comment by vchitike** [comment]
@lenny-intel I need to add secure token as a header for rest-api execution. That's separate thing.
But for the issue I am talking about here is getting 401-unauthorized while creating camera credentials using map_crdentials.sh.
When we execute map_crdentials sh first thing it prompts for acl-consul-token, after providing that token it asks credentials name, user name and password, and then finally when try to save crdentials and exit script it gives '401- unauthorized' error.

Do we need to give jwt token as a header while executing map_crdentials.sh script? I don't think scripts are updated. 
BTW it works correctly (meant no authorization error) with onvif main branch.

**Comment by ajcasagrande** [comment]
> Do we need to give jwt token as a header while executing map_crdentials.sh script? I don't think scripts are updated.
BTW it works correctly (meant no authorization error) with onvif main branch.

Yes, in secure mode the device service's `/api/v2/secret` endpoint is called. Any new authentication methods will need to be provided by the script now as well.

**Review by ajcasagrande — COMMENTED** [review]
The actual code changes here looks fine, but seems like some validation issues around the changes in the sdk itself.

**Comment by ajcasagrande** [comment]
@vyshali-chitikeshi @weichou1229 updated scripts to support jwt for rest apis can be found in my PR against this PR's branch, here:

https://github.com/weichou1229/device-onvif-camera/pull/1

**Comment by vchitike** [comment]
Thanks Anthony for updating scripts.
I just validated https://github.com/weichou1229/device-onvif-camera/pull/1#pullrequestreview-1346649923 and it looks good. able to create credentials successfully with map_credentials script and api execution also works correctly

**Comment by weichou1229** [comment]
> @vyshali-chitikeshi @weichou1229 updated scripts to support jwt for rest apis can be found in my PR against this PR's branch, here:

Thanks for your help! I merged the commit.

**Review by presatish — APPROVED** [review]

**Pull request merged**
