### PR TITLE
fix: upgrade sdk to fix device cache issue

### PR DESCRIPTION
**Pull request by ajcasagrande**
**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [N/A] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [N/A] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

- make test
- make docker
- /compose-builder$ git checkout levski
- /compose-builder$ make pull
- /compose-builder$ make gen no-secty ds-onvif-camera (this generates docker-compose.yml with levski based edgex images)
- Replace onvif service docker image in docker-compose.yml with your latest image created using `make docker` from the previous step
- /compose-builder$ make up
- /bin/configure-subnets.sh without error
- /bin/map-credentials.sh without error
- Onvif devices should be registered in Edgex
- Sending any valid command to the onvif device should be successful
- Restart the onvif docker service
- Re-sending commands to the device as done previously should be successful

### CODE REVIEW

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Comment by lenny-goodell** [comment]
@ajcasagrande , please add the testing instructions

**Review by presatish — APPROVED** [review]

**Comment by presatish** [comment]
> @ajcasagrande , please add the testing instructions

I have added testing instructions in the usual way we add in Edgex, you can modify as you need.

**Comment by vchitike** [comment]
Validation looks good.

**Pull request merged**
