### PR TITLE
build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

### PR DESCRIPTION
**Pull request by lenny-goodell**
**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **N/A**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
      <link to docs PR>

## Testing Instructions
verify make docker works
Run non-secure EdgeX stack 
Build and run service from command line
Verify logs have no errors bootstrapping.

### CODE REVIEW

**Comment by ajcasagrande** [comment]
@lenny-intel should we add the go version to the Jenkinsfile like we did for levski?

**Comment by lenny-goodell** [comment]
> @lenny-intel should we add the go version to the Jenkinsfile like we did for levski?

Does seem to be a good practice that way it is there when we create the branch. I'll ping @ernestojeda to see what he thinks.

**Comment by lenny-goodell** [comment]
@ajcasagrande , nope since we don't always create a release branch.

**Comment by presatish** [comment]
Do we need to add any of these changes in `CHANGELOG.md`?

**Comment by lenny-goodell** [comment]
> Do we need to add any of these changes in `CHANGELOG.md`?

@presatish , The change log gets updated from a generated change log prior to release.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
